version: 2.0
jobs:
  test:
    docker:
      - image: python:3.7-slim-stretch
    steps:
      - checkout
      - run:
          name: Install pipenv
          command: pip3 install --user pipenv
      - run:
          name: Install dependencies
          command: pipenv run install --dev
      - run:
          name: Run tests
          command: pipenv run pytest
